name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - trim-galore=0.6.2
  - samtools=1.9
  - star=2.7.3a
  - rseqc=3.0.1
  - ldc=1.13.0
  - sambamba=0.7.0
  - samblaster=0.1.24
  - multiqc=1.7
  - htseq=0.11.2 
