name: rnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6.0
  - fastqc=0.11.8
  - cutadapt=1.18
  - trim-galore=0.5.0

  - multiqc=1.7
  - samtools=1.9
  - star=2.6.1b
  - rseqc=3.0.0
  - sambamba=0.6.8
  - samblaster=0.1.24
